name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish -c Release -o ${{ github.workspace }}/publish --no-restore

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: noeflix
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
        package: ${{ github.workspace }}/publish
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
