name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'

    - name: Build .NET Backend
      run: |
        cd backend
        dotnet restore
        dotnet build --configuration Release
        dotnet publish --configuration Release --output ./publish

    - name: Build React Frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Deploy .NET Backend
      uses: azure/webapps-deploy@v2
      with:
        app-name: '<your-dotnet-app-service-name>'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './backend/publish'

    - name: Deploy React Frontend
      uses: azure/static-web-apps-deploy@v1
      with:
        app_location: './frontend'
        output_location: './frontend/build'
        token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }
